### ISSUE TITLE
Error in absolute path when using Docker 1.6 on Windows 7

### ISSUE THREAD

**Issue by joao-parana** [dduportal-dockerfiles/docker-compose#1]
I'm trying to execute de command

```
docker run -v "$(pwd)":/app -v /var/run/docker.sock:/var/run/docker.sock -ti dduportal/docker-compose:latest --help 
```

but I'm getting the Error:

```
invalid value "c:\\Users\\user\\docker\\myFirstService;C:\\Program Files (x86)\\Git\\app" for flag -v: \Users\user\docker\myFirstService;C:\Program Files (x86)\Git\app is not an absolute path
See 'c:\Program Files\Boot2Docker for Windows\docker.exe run --help'.
```

I´m runnig inside the MINGW32 shell open by Boot2Docker start.lnk instaled in my Desktop 

What is going wrong ?

**Comment by dduportal** [comment]
Hi @joao-parana !

It seems related to Windows/MinGW32 path conversion at the call. Maybe an updated documentation will be needed seems docker is know officially supported on Windows.

Just to help me (and others future concerned users), could you show me what you have for those commands, in the same context (same folder, same docker, same host, etc. ) :
- `pwd`
- `echo "$(pwd)"`

?

**Comment by dvh** [comment]
Hi @dduportal,

I have the same problem on Windows 8.1, so I will answer your question with my values:
- `/c/` (when I am in my C:\ folder)
- `/c/newFolder/` (when I am in C:\newFolder)

Same values for `echo "$(pwd)"` :-(

**Comment by joostfarla** [comment]
This is related to issue https://github.com/docker/docker/issues/12590. In Windows, the host path has to be prepended with an extra slash, otherwise msysgit will convert the path to a wrong value. So the actual docker command has to look like this:

```
docker run -v /$(pwd):/app ...
```

I guess this has to be modified in the way Docker Compose generates the volume path.

**Comment by dduportal** [comment]
Hi all !

Thanks for you feedback.

As of @joostfarla comment, i've updated the documentation to help that.

Don't hesitate to re-open the issue if it does not work for you.
