### ISSUE TITLE
Secret ENV variables don't work

### ISSUE THREAD

**Issue by sherter** [dduportal-dockerfiles/docker-compose#14]
```
# docker-compose.yml
mysql:
  image: mysql
  environment:
  - MYSQL_ROOT_PASSWORD
```

```
$ env |grep MYSQL
MYSQL_ROOT_PASSWORD=password
$ dc up
Creating test_mysql_1...
Attaching to test_mysql_1
mysql_1 | error: database is uninitialized and MYSQL_ROOT_PASSWORD not set
mysql_1 |   Did you forget to add -e MYSQL_ROOT_PASSWORD=... ?
test_mysql_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
```

When I write `MYSQL_ROOT_PASSWORD=password` instead everything works fine, but exported env variables are not "forwarded" from host to the docker-compose container. Has somebody an idea how to solve this?

**Comment by dduportal** [comment]
Hello @sherter !

Can you provide me the version of docker Engine and docker-compose you're using ?

I'm currently building a 1.3.3 version for this image, to be up-to-date with latest compose, i'll keep you informed here.

Also, do you have the opportunity to test this with a "vanilla" docker-compose to confirm that this is related to my image ?

**Comment by sherter** [comment]
It is not directly a problem with the image, but how one uses it. The suggested alias will not allow you to use [secret environment variables](https://docs.docker.com/compose/yml/#environment), because the host environment is not forwarded to the container.

Adding `$(env | sed "s/^/-e /")` to the alias fixes this problem:

```
# ~/.bashrc
alias dc='docker run -v $(pwd):/app -v /var/run/docker.sock:/var/run/docker.sock $(env | sed "s/^/-e /") -e COMPOSE_PROJECT_NAME=$(basename $(pwd)) -ti --rm dduportal/docker-compose:latest'
```

**Comment by dduportal** [comment]
Thansk for reproting your solution !

I closed since it does not seems related to the tool.

You should try to play with [Vault](https://vaultproject.io) from Hashicorp to store password encrypted :)
If you are doing only dev : use simple password, no need to complex ones :)
