### ISSUE TITLE
Unable to mount volumes since installing Docker Toolbox on Windows

### ISSUE THREAD

**Issue by AustinMaddox** [dduportal-dockerfiles/docker-compose#16]
Last week when I was using Boot2docker, everything worked fine. Is it just me or is there no way to run docker-compose inside a container like this anymore with the [Docker Toolbox](https://www.docker.com/toolbox)?

From the _Git Bash_ Docker Quickstart Terminal...

```
$ docker run -it --rm -v "$(pwd)":/app -v /var/run/docker.sock:/var/run/docker.sock dduportal/docker-compose up -d
invalid value "c:\\Users\\austin;C:\\Program Files (x86)\\Git\\app" for flag -v: bad mount mode specified : \Program Files (x86)\Git\app
See 'c:\Program Files\Docker Toolbox\docker.exe run --help'.
```

I'm running 64-bit Windows 7.

```
$ docker -v
Docker version 1.8.1, build d12ea79
```

**Comment by michalpristas** [comment]
same here.
installed docker tools 1.8.1c
MINGW64 on windows 8.1

 docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

**Comment by bweston92** [comment]
I get this issue too, Windows 10.

**Comment by dduportal** [comment]
Hello !

I'll try to reproduce that, time for me to have at least a Windows 7 working (sorry, don't have Win 10 licence)

Is it possible to test as soon as I'll have something ?

**Comment by AustinMaddox** [comment]
The temporary fix is avoid using `"$(pwd)"` and provide absolute paths with an extra `/` in front of them. Don't ask me _why_ that works, I researched all over the internet for that strange workaround.

From the _Git Bash_ Docker Quickstart Terminal...

```
$ docker run -it --rm -v //c/Users/your/path/to/app:/app -v //var/run/docker.sock:/var/run/docker.sock dduportal/docker-compose up -d
```

**Comment by tryjude** [comment]
Thanks @austin881. That solved my problem!

**Comment by dduportal** [comment]
Seems OK after :
- This PR : https://github.com/dduportal-dockerfiles/docker-compose/pull/17
- And this issue closed : https://github.com/dduportal-dockerfiles/docker-compose/issues/1

Both have pushed changes for usage in Windows.
Just tried on a fresh Win 10, and it's OK with the latest docker-toolbox (1.9.0).
