### ISSUE TITLE
cannot enable tty mode on non tty input

### ISSUE THREAD

**Issue by AustinMaddox** [dduportal-dockerfiles/docker-compose#18]
Ever since installing the latest version of the Docker Toolbox ([v1.8.2](https://github.com/docker/toolbox/releases))

When I run...

```
docker run -v "/$(pwd)":/app \
    -v //var/run/docker.sock:/var/run/docker.sock \
    -e COMPOSE_PROJECT_NAME=$(basename "$(pwd)") \
    -ti --rm \
    dduportal/docker-compose:latest --help
```

I am given this message...

> cannot enable tty mode on non tty input

I'm running 64-bit Windows 7.

```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

Any ideas? I can work around the issue by omitting the `-i` or `-t` but I'm not sure why I'm given the message in the first place. It makes `docker-compose rm` difficult because it asks for interaction "Are you sure? [yN]" .

**Comment by AustinMaddox** [comment]
Disregard, I jumped to conclusions. This is an upstream bug.

Docker Toolbox
["cannot enable tty mode on non tty input" when trying to run -it ubuntu bash 1.8.1c. #136](https://github.com/docker/toolbox/issues/136)

Docker
["cannot enable tty mode on non tty input" in Cygwin in Windows #12469](https://github.com/docker/docker/issues/12469)

**Comment by tiangolo** [comment]
I wrote a simple workaround / quick fix to allow using Docker Toolbox from Babun, it may help you:

https://github.com/tiangolo/babun-docker

With that you can keep using your docker commands as normal.

And if you are using Cygwin, you should use Babun, a very improved version of Cygwin.

You just have to run one command to setup everything. Although I encourage you to check the source code before running any script (including mine) in your terminal.

Inside, it installs and sets up winpty, and tries to start your default docker-machine VM and set up its environment.
